---
- hosts: client

#Ansible configure target machine from host list "server" through SSH connection
#clone down the repository and deploy the app using kubernetes by giving it the yaml file
#original deployment is 3 replicas, later scale it up to 5

  tasks:

     - name: remove existing repository
       shell: rm -rf Case-Study-Part-2

     - name: pull repository
       shell: git clone https://github.com/kg0529/Case-Study-Part-2.git

     - name: deploy flask-application  3 relicas
       shell: kubectl apply -f ~/Case-Study-Part-2/kubernetes.yml

     - name: scale up flask-app
       shell: kubectl scale deployment/flask-deployment --replicas=5
